### PR TITLE
Merge & subsequent alignments of SensemakerStore tests

### LINKED ISSUE #51: Add Assessment ID into zome return value
When we are receiving assessments from the Sensemaker, we do not have a unique identity for each datum. We are only receiving either the record or the Assessment object without its entry hash (except for when we create a particular assessment, then we receive only the entry hash and guess at some of the other fields).

This means that if we happen to retrieve an assessment multiple times (either from a signal and a request or multiple requests), then we have no way of disambiguating between duplicates.

We should get all assessments with an entry hash in string form.

The main reason I can see for why we never started doing this is because we've assumed that everything received or retrieved is unique and immutable. I'm not sure this is enforced or always the case. However, in order to ensure an applet requesting/receiveing the same information twice doesn't end up getting the data twice, we need a more sophisticated approach.

We should also make sure creating an assessment returns the full hash and object. Currently we are creating a random timestamp from some time in the future and applying that to the object which can lead to inconsistencies.

### PR DESCRIPTION
**Pull request by pospi**
(previously implemented in #41)

### CODE REVIEW

**Comment by pospi** [comment]
I doubt they'll pass yet, just wanted to get through the initial history management.

**Comment by weswalla** [comment]
I'm going to make time to go through this PR in more depth, although I may need a little help wrapping my head around the RxJS stuff and related tests ;)

On a broader note, there is another possibly challenging merge (at least, will involve some manual conflict resolution) ahead with #44 , I think mostly to with updating the signal handling to conform to our new state model.

There are also changes in #49 which include a new stateful property `WidgetRegistry`, which we will have to update to use the new reactive binding pattern.

**Comment by pospi** [comment]
@adaburrows I think this is ready for some of your dev input, if you're willing to spend the time on it. A lot of the test errors are at typechecker level at present; and they're a result of missing convenience methods I'd implemented on my branch not being present here. If you were to implement them then probably >50% of the errors would be gone.

If you like, I can wait while you work through that and we can make an assessment but I could also go ahead in #41 to get tests passing again and then copy-paste my whole `SensemakerStore` over what's in #46. Please advise?

Feel free to merge this branch at any time from here forward- I'm happy with the progress made and IIRC it's a step further along than the absence of passing tests prior.

Also note that PNPM configuration is cherry-picked in; and thus an `npm run clean:modules && pnpm i` are required after pulling latest changes.

**Comment by pospi** [comment]
Ready to merge if we're happy to proceed on the remaining API refactor / redesign work via getting the remaining tests to pass.

```
  85 tests
  87 passed
  13 failed  

  Failed Tests:   There were 13 failures

    x TypeError: run is not a function
    x TypeError: run is not a function
    x TypeError: store.assessmentsForResource is not a function
    x TypeError: store.assessmentsForDimension is not a function
    x should be truthy
    x should be deeply equivalent
    x should be truthy
    x should be truthy
    x should be deeply equivalent
    x should be deeply equivalent
    x should be deeply equivalent
    x should be deeply equivalent
    x should be deeply equivalent
```

The 6 "should be deeply equivalent" errors are a result of differing return types from `SensemakerService` (`EntryHash` vs `EntryHashB64`).

**Comment by adaburrows** [comment]
I'm going to manually cherry pick needed commits, since I already have much of what you squashed into this from a rebase after using some other tool that rewrote all the commit hashes, like git-filter-* and related history rewriting tools.

**Pull request closed without merging**
