### PR TITLE
tabular primitives in store

### LINKED ISSUE #73: switch to tabular representation of SM primitives in SM Store
Currently, all primitives are stored in the store under an applet config keyed by the applet name:

```typescript
  _appletConfigs: Writable<{ [appletName: string]: AppletConfig}> = writable({});
  
export interface AppletConfig {
    name: string,
    ranges: {
        [rangeName: string]: EntryHash,
    },
    dimensions: {
        [dimensionName: string]: EntryHash,
    },
    resource_defs: HappZomeMap<{
        [resourceDefName: string]: EntryHash,
    }>,
    methods: {
        [methodName: string]: EntryHash,
    },
    cultural_contexts: {
        [contextName: string]: EntryHash,
    }
}
```

this was done for easy access to entry hashes and applet info, however, this has a few limitations, the main one being there is no sensible way of storing primitives that are created directly within the NH-Launcher itself, since they don't belong to an applet.

I think we can do away with the concept of an "applet config" as a entry type in the SM zome (https://github.com/neighbour-hoods/sensemaker-lite/blob/4ec65918052fd34386a9768ad4f44091a5ae8606/dnas/sensemaker/zomes/integrity/sensemaker/src/applet.rs#L12-L20) and instead replace it with a representation of an "Applet" and then primitives can include a field `source` which includes whether or not this primitive was defined in an applet bundle. Then, if on the client side we need to display any primitives that came from an applet (like in the dashboard) that can be a derived list by filtering our primitives with sources that do not match the selected applet.

I propose that we make the following changes to make it simpler to deal with SM primitives in the launcher:

```typescript

interface Applet {
    name: String,
    applet_entry_hash: EntryHash, // the entry hash of the Applet entry in the Applet Zome (https://github.com/neighbour-hoods/nh-launcher/blob/808a9d7f6bc6c30de944e184465563f1838e7e70/dnas/we/zomes/integrity/applets/src/lib.rs#L29-L44)
    installed_app_id?: String // if it is important to know how the happ was registered to the conductor
}

export class SensemakerStore {

// the following stores are keyed by hash rather than being arrays to avoid duplicates
// perhaps the following should be one writable store and then each property becomes a key in that object
  _applets: Writable<{ [entryHash: string]: Applet}> = writable({});
  _ranges: Writable<{ [entryHash: string]: Range}> = writable({});
  _dimensions: Writable<{ [entryHash: string]: Dimension}> = writable({});
  _methods: Writable<{ [entryHash: string]: Method}> = writable({});
  _contexts: Writable<{ [entryHash: string]: Context}> = writable({});
// OR
_primitives: Writable< {
  _applets: { [entryHash: string]: Applet },
  _ranges: { [entryHash: string]: Range },
  _dimensions: { [entryHash: string]: Dimension },
  _methods: { [entryHash: string]: Method} , 
  _contexts: { [entryHash: string]: Context }
} = writable({});

...

}
```

Additionally, there are various approaches to including the source applet of each primitive, by either adding that field, or since it is a generic and shared field, we could create a generic type:

```rust
struct Primitive<T> {
    source: EntryHash // of the applet entry
    entry: T
}
```
We will also need a representation of Assessments and Resource Definitions, however, this can be outlined in different tickets.

### PR DESCRIPTION
**Pull request by weswalla**
closes #73 

- [ ] update changelogs to reflect changes
- [ ] update version numbers and publish (once tested)

### CODE REVIEW

**Comment by adaburrows** [comment]
Do you still need to update the changelogs?

**Comment by weswalla** [comment]
@adaburrows 
> Do you still need to update the changelogs?

yes. I can do that. Do we want to publish it as well?

**Comment by weswalla** [comment]
I've updated the changelogs. Once these are approved, we can tag, publish, and make a github release.

**Review by pospi — APPROVED** [review]
Looks to be followed through to completion to me, based on the discussion we had on the 20th/21st (:

**Pull request closed without merging**
