### PR TITLE
Basic CRUD of all entry types

### PR DESCRIPTION
**Pull request by weswalla**
The goal of this PR is to write the first pass at the Sensemaker-lite, including testing of the coordinator zome API.

### CODE REVIEW

**Comment by weswalla** [comment]
@adaburrows @tatssato @juliolrmonteiro not sure exactly why, but the tests are not consistent. Like the DNA is not be registered some of the runs, because some of the runs give the following error:
```
{
  type: 'error',
  data: {
    type: 'internal_error',
    data: "ZomeError: Zome not found: Zome 'test_provider' not found"
  }
}
```
But then some of the times it passes fine.

**Comment by tatssato** [comment]
Looks good to me so far. 
I made some folder structure changes to clearly separate the 2 dnas we have. 
Trying to get access to the repository so that I can open up a PR for this branch.

**Comment by julioholon** [comment]
Hey there @weswalla. do you think it's safe to merge this into master develop, this is very advanced already and seems stable enough to call it done, right? What else do you need?

**Comment by weswalla** [comment]
hey @julioholon I think that should be fine...

**Pull request merged**
